hashtags:
  - perfumemexico
  - perfumesmexico
  - fraganciasmexico
  - perfumesdemujer
  - perfumessolidos
  - bellezamexicana
  - bellezamexico
  - maquillajemexico
  - skincaremexico
  - cuidadodelapielmx
  - beautybloggermexico
  - bloggeramexicana
  - creadoradecontenidomx
  - ugcmexico
  - lifestylemexico
  - modamexicana
  - cdmxblogger
  - mexicoblogger
